App\Entity\Passwords:
  collectionOperations:
    get_counts:
      method: 'POST'
      path: '/passwords'
      controller: App\Controller\PasswordController
      defaults:
        _api_receive: false
      openapi_context:
        tags:
          - Passwords
        summary: checks a password
        description: |
          Checks a password
        operationId: searchLogs
        requestBody:
          content:
            application/json:
              schema:
                type: object
                properties:
                  password:
                    type: string
                required:
                  - password
        responses:
          "200":
            description: count of matching results
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    count:
                      type: number
          "400":
            description: bad input parameter
  itemOperations: []
