<?php

namespace App\Tests\Command;

use App\Service\Password\PasswordService;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Tester\CommandTester;

class BatchValidationTest extends KernelTestCase
{
    private CommandTester $commandTester;
    private PasswordService $passwordService;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $kernel = self::bootKernel();
        $testContainer = $kernel->getContainer()->get('test.service_container');
        $this->passwordService = $testContainer->get(passwordService::class);

        $this->assertSame('test', $kernel->getEnvironment());

        $application = new Application($kernel);
        $command = $application->find('bath-validation');
        $this->commandTester = new CommandTester($command);

    }

    public function testSuccessMessage(): void
    {
        $this->commandTester->execute([]);
        $this->commandTester->assertCommandIsSuccessful();
        $output = $this->commandTester->getDisplay();
        $this->assertStringContainsString('All the passwords has been validated.', $output);
    }
}
