<?php

namespace App\Tests\Controller;

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;

class PasswordControllerTest extends ApiTestCase
{
    private $client;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->client = static::createClient();
    }

    public function testApiEndpoint(): void
    {
        $response = $this->client->request('GET', '/');
        $this->assertResponseIsSuccessful();
    }

    public function testPasswordApi(): void
    {
        $body = ['password' => ''];
        $response = $this->client->request('POST', '/passwords', ['body' => $body]);
        $this->assertResponseStatusCodeSame(400);
    }
}
